version = 1
SPDX-PackageName = "AdGuard Mini"
SPDX-PackageSupplier = "AdGuard Software Limited <devteam@adguard.com>"
SPDX-PackageDownloadLocation = "https://github.com/AdguardTeam/AdguardForSafari"

[[annotations]]
path = ["**/*.png", "**/*.svg", "**/*.pdf", "**/*.xcassets/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Media Kit"

[[annotations]]
path = ["**/locales/*.json", "**/*.strings"]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Translations"

[[annotations]]
path = ["AdguardMini/SciterResources/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Sciter resources"

[[annotations]]
path = [
    "**/*.json",
    "**/*.xcconfig",
    "**/*.pbxproj",
    "**/*.xcscheme",
    "**/*.xcworkspace/**",
    "**/*.xcodeproj/**",
    "**/*.entitlements",
    "**/*.plist",
    "**/.eslintignore",
    "**/Package.swift",
    "requirements.txt",
    "**/README.md",
    "DEVELOPMENT.md",
    ".localecheckerrc",
    ".lintstagedrc.js",
    ".husky/**",
    "**/*.html",
    "AdguardMini/sciter-ui/modules/inline/**",
    "AdguardMini/AdguardMini/Resources/ThirdPartyDependencies.md",
    "docs/safari-filters-update-flow.md",
    "AdguardMini/AdguardMiniTests/UrlFilteringCheckerTests/Filter1.txt",
    "AdguardMini/sciter-js-sdk/**",
    "AdguardMini/WebExtension/Resources/**",
    "AdguardMini/PopupExtension/ContentScript/rollup.config.ts",
    "AdguardMini/PopupExtension/ContentScript/src/index.ts",
    "AdguardMini/PopupExtension/ContentScript/src/logger.ts",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "adguard-mini-private-template/**",
    "Support/XcodeTemplates/**",
    ".github/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    ".windsurf/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [
    "AdguardMini/sciter-ui/schema/**/*.proto"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Protocol Buffers schema definitions"

[[annotations]]
path = [
    "AdguardMini/SciterResources/SciterSchema/Sources/**/*.swift"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Generated from proto schemas"

[[annotations]]
path = [
    "AdguardMini/sciter-ui/modules/common/apis/types/**/*.ts",
    "AdguardMini/sciter-ui/modules/common/apis/services/**/*.ts",
    "AdguardMini/sciter-ui/modules/common/apis/callbacks/**/*.ts"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "AdGuard Software Limited"
SPDX-License-Identifier = "GPL-3.0-or-later"
SPDX-FileComment = "Generated from proto schemas"

[[annotations]]
path = [
    "build/**",
    "*.xcworkspace/**",
    "*.xcodeproj/**",
    "DerivedData/**",
    "**/*.resolved",
    "**/*.lock"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = "Dependency files"
