# SPDX-FileCopyrightText: AdGuard Software Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

---
version: 2
deployment:
  name: AdGuard Mini for Mac MAS
deployment-permissions:
- roles:
  - logged-in
  permissions:
  - view
- users:
  - am
  groups:
  - mac-developers
  permissions:
  - view
  - edit
environment-permissions:
- MAS:
  - roles:
    - logged-in
    permissions:
    - view
  - users:
    - am
    - v.bachinskiy
    groups:
    - mac-developers
    permissions:
    - view
    - edit
    - deploy
